<?php
	/*!
	 * Email template.
	 * 
	 * @since 1.0.4 Modified Generated By output to use new setting.
	 * @since 1.0.0
	 * 
	 * @package InvoiceEM
	 */

	if (!defined('ABSPATH'))
	{
		exit;
	}
	
	$iem = InvoiceEM();
	$transparent = esc_url(InvoiceEM()->cache->asset_path('images', 'transparent.gif'));
	
	$direction = (is_rtl())
	? ' style="direction: rtl;"'
	: '';
?>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
	
		<meta http-equiv="Content-Type"  content="text/html charset=UTF-8" />
		
		<title>%email_subject%</title>
		
		<style type="text/css">
		
			body
			{
				margin: 0;
				padding: 0;
				min-width: 100% !important;
			}
			
			img
			{
				height: auto;
				width: auto;
				max-width: 100%;
			}
			
			.wrap
			{
				width: 100%;
				max-width: 600px;
				min-width: 300px;
			}
			
			@media (min-width: 601px)
			{
				.wrap
				{
					width: 600px !important;
				}
			}
			
		</style>
		
	</head>
	
	<body bgcolor="#dddddd" style="background-color: #ddd;">
	
		<div<?php echo $direction; ?>>
		
			<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#dddddd" style="background-color: #ddd;">
				<tr>
					<td>
					
						<!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" align="center" width="600">
							<tr>
								<td><![endif]-->
								
									<table border="0" cellpadding="0" cellspacing="0" align="center" class="wrap">
										<tr>
											<td bgcolor="#cccccc" height="1" rowspan="5" width="1" style="background-color: #ccc; line-height: 1px;"><img src="<?php echo $transparent; ?>" height="1" width="1" alt="" style="display: block;" /></td>
											<td bgcolor="#cccccc" width="100%" style="background-color: #ccc; line-height: 1px;"><img src="<?php echo $transparent; ?>" height="1" width="1" alt="" style="display: block;" /></td>
											<td bgcolor="#cccccc" rowspan="5" width="1" style="background-color: #ccc; line-height: 1px;"><img src="<?php echo $transparent; ?>" height="1" width="1" alt="" style="display: block;" /></td>
										</tr>

										<tr>
											<td bgcolor="#eeeeee" style="background-color: #eee;">
												<table border="0" cellpadding="0" cellspacing="0" width="100%">
													<tr>
														<td height="10" rowspan="3" width="20" style="line-height: 10px;"><img src="<?php echo $transparent; ?>" height="10" width="20" alt="" style="display: block;" /></td>
														<td width="100%" style="line-height: 10px;"><img src="<?php echo $transparent; ?>" height="10" width="20" alt="" style="display: block;" /></td>
														<td rowspan="3" width="20" style="line-height: 10px;"><img src="<?php echo $transparent; ?>" height="10" width="20" alt="" style="display: block;" /></td>
													</tr>

													<tr>
														<td style="color: #282828; font-family: Arial, sans-serif; font-size: 21px; line-height: 29px;"><strong>%email_title%</strong></td>
													</tr>

													<tr>
														<td height="10" style="line-height: 10px;"><img src="<?php echo $transparent; ?>" height="10" width="20" alt="" style="display: block;" /></td>
													</tr>
												</table>
											</td>
										</tr>

										<tr>
											<td bgcolor="#ffffff" style="background-color: #fff;">
												<table border="0" cellpadding="0" cellspacing="0" width="100%">
													<tr>
														<td height="20" rowspan="3" width="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
														<td width="100%" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
														<td rowspan="3" width="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
													</tr>

													<tr>
														<td style="color: #4c4c4c; font-family: Arial, sans-serif; font-size: 14px; line-height: 19px;">%email_content%</td>
													</tr>

													<tr>
														<td height="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
													</tr>
												</table>
											</td>
										</tr>

										<tr>
											<td bgcolor="#eeeeee" style="background-color: #eee;">
												<table border="0" cellpadding="0" cellspacing="0" width="100%">
													<tr>
														<td height="20" rowspan="5" width="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
														<td width="100%" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
														<td rowspan="5" width="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
													</tr>

													<tr>
														<td style="color: #282828; font-family: Arial, sans-serif; font-size: 14px; line-height: 19px;"><?php InvoiceEM_Output::company_logo(); ?></td>
													</tr>

													<tr>
														<td height="10" style="line-height: 10px;"><img src="<?php echo $transparent; ?>" height="10" width="1" alt="" style="display: block;" /></td>
													</tr>

													<tr>
														<td style="color: #282828; font-family: Arial, sans-serif; font-size: 14px; line-height: 19px;"><?php InvoiceEM_Output::company_information(); ?></td>
													</tr>

													<tr>
														<td height="20" style="line-height: 20px;"><img src="<?php echo $transparent; ?>" height="20" width="20" alt="" style="display: block;" /></td>
													</tr>
												</table>
											</td>
										</tr>
										
										<?php if ($iem->settings->general->show_generated_by) : ?>
										
											<tr>
												<td bgcolor="#cccccc" style="background-color: #ccc;">
													<table border="0" cellpadding="0" cellspacing="0" width="100%">
														<tr>
															<td height="5" rowspan="3" width="20" style="line-height: 5px;"><img src="<?php echo $transparent; ?>" height="5" width="20" alt="" style="display: block;" /></td>
															<td width="100%" style="line-height: 5px;"><img src="<?php echo $transparent; ?>" height="5" width="20" alt="" style="display: block;" /></td>
															<td rowspan="3" width="20" style="line-height: 5px;"><img src="<?php echo $transparent; ?>" height="5" width="20" alt="" style="display: block;" /></td>
														</tr>

														<tr style="vertical-align: top;">
															<td style="color: #000; font-family: Arial, sans-serif; font-size: 11px; line-height: 15px; text-align: center;">

																<?php
																	$link = '<a href="https://invoiceem.com" target="_blank" rel="noopener noreferrer" style="color: #0073aa;">';

																	echo str_replace
																	(
																		'  ',
																		'&nbsp; ',

																		sprintf
																		(
																			__('Email Generated by %1$s  |  %2$s', 'invoiceem'),
																			$link . $iem->cache->plugin_data['Name'] . '</a>',
																			$link . 'https://invoiceem.com</a>'
																		)
																	);
																?>

															</td>
														</tr>

														<tr>
															<td height="4" style="line-height: 4px;"><img src="<?php echo $transparent; ?>" height="4" width="20" alt="" style="display: block;" /></td>
														</tr>
													</table>
												</td>
											</tr>
											
										<?php endif; ?>
										
										<tr>
											<td bgcolor="#cccccc" style="background-color: #ccc; line-height: 1px;"><img src="<?php echo $transparent; ?>" height="1" width="1" alt="" style="display: block;" /></td>
										</tr>
									</table>
									
								<!--[if (gte mso 9)|(IE)]></td>
							</tr>
						</table><![endif]-->
						
					</td>
				</tr>
			</table>
			
		</div>
		
	</body>
	
</html>
